services:
  ros2_lecture_jazzy_lxqt:
    container_name: ros2_lecture_jazzy_lxqt
    image: kmiyawaki20/ros2_jazzy_lxqt:202604
    devices:
      - /dev/dxg:/dev/dxg
    volumes:
      - ubuntu:/home/ubuntu
      - ./share/data:/home/ubuntu/data
      - /usr/lib/wsl:/usr/lib/wsl
    ports:
      - "6080:80"
      - "5901:5901"
    environment:
      - USER=ubuntu
      - TZ=Asia/Tokyo
      - NO_AT_BRIDGE=1
    tty: true
volumes:
  ubuntu:
